/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BeliefLabel {
    id: number;
    description: string;
    type: 'internal' | 'external';
    explanation: string | null;
    evidence?: string | null;
    disputation?: string | null;
    new_perspective?: string | null;
} 