/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Element } from "./element";

export interface BeliefExplanation extends Element {
    type: "belief";
    description: string;  // 説明文
}

export interface BeliefAnalysisResult {
    labels: BeliefExplanation[];  // 3つの説明を含む配列
}

export interface BeliefAnalysisResponse {
    belief_analysis: BeliefAnalysisResult;
} 