/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ConcludeFailureInput {
	failure_id: number;
	selected_label: string;
	adversity: string;
	belief_explanation: string;
	dispute_evidence: string;
	dispute_counter: string;
}
