/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ElementType } from './elementType';

export interface Element {
  id: number;
  description: string;
  type: ElementType;
  created_at: string;
}
