/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ElementType = (typeof ElementType)[keyof typeof ElementType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ElementType = {
	adversity: "adversity",
	belief: "belief",
	consequence: "consequence",
	disputation: "disputation",
	effect: "effect",
} as const;
