/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Failure } from "./failure";

export type GetFailureByIdFailureFailureIdGet200 = Failure | null;
