/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user';

export type GetUserByFirebaseUidUserFirebaseUidGet200 = User | null;
