/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Element } from "./element";

export type SuggestElementsElementsSuggestPost200 = Element[] | null;
