/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BeliefLabel } from "./beliefLabel";

export type SuggestInputSelectedLabel = BeliefLabel | null;
