/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Element } from "./element";
import type { BeliefAnalysisResponse } from "./beliefAnalysisResponse";

export type SuggestElementsElementsSuggestPost200 = Element[] | BeliefAnalysisResponse | null;
