/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ElementType } from './elementType';
import type { Element } from './element';
import type { SuggestInputSelectedLabel } from './suggestInputSelectedLabel';

export interface SuggestInput {
  text: string;
  type: ElementType;
  elements: Element[];
  selected_label?: SuggestInputSelectedLabel;
}
