/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Element } from './element';
import type { ElementType } from './elementType';

export interface SummarizeInput {
  elements: Element[];
  analysis_type: ElementType;
}
