"""model

Revision ID: 26468e89757c
Revises: 7ec9a1730f87
Create Date: 2025-03-06 10:11:18.940309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26468e89757c'
down_revision: Union[str, None] = '7ec9a1730f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('failures', sa.Column('hero_failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'hero_failure_reason')
    op.drop_column('failures', 'reason')
    # ### end Alembic commands ###
