"""model

Revision ID: 7ec9a1730f87
Revises: 94ceb1d778a0
Create Date: 2025-03-06 10:10:08.242576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec9a1730f87'
down_revision: Union[str, None] = '94ceb1d778a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('has_analyzed', sa.Boolean(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hero_name', sa.Text(), nullable=True),
    sa.Column('hero_description', sa.Text(), nullable=True),
    sa.Column('hero_failure', sa.Text(), nullable=True),
    sa.Column('hero_failure_source', sa.Text(), nullable=True),
    sa.Column('hero_failure_certainty', sa.Float(), nullable=True),
    sa.Column('explain_certainty', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_id'), 'failures', ['id'], unique=False)
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('ADVERSITY', 'BELIEF', 'DISPUTATION', name='elementtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('failure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['failure_id'], ['failures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_id'), 'elements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elements_id'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_failures_id'), table_name='failures')
    op.drop_table('failures')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
