"""url

Revision ID: b1d5fcb6eada
Revises: b531f4d471dc
Create Date: 2025-03-07 13:27:21.865005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d5fcb6eada'
down_revision: Union[str, None] = 'b531f4d471dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('hero_energy', sa.Text(), nullable=True))
    op.add_column('failures', sa.Column('hero_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'hero_image_url')
    op.drop_column('failures', 'hero_energy')
    # ### end Alembic commands ###
