"""add models

Revision ID: f64a54526f2e
Revises: 2a4c9720da7e
Create Date: 2025-02-25 02:38:44.359365

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Enum

# revision identifiers, used by Alembic.
revision: str = "f64a54526f2e"
down_revision: Union[str, None] = "2a4c9720da7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("firebase_uid", sa.String(128), nullable=False, unique=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )

    op.create_table(
        "failures",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("self_score", sa.Integer(), nullable=False),
        sa.Column("has_analyzed", sa.Boolean(), default=False),
        sa.Column("conclusion", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )

    op.create_table(
        "elements",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            Enum("INTERNAL", "EXTERNAL", "EMOTIONAL", name="elementtype"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "failure_id",
            sa.Integer(),
            sa.ForeignKey("failures.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("elements")
    op.drop_table("failures")
    op.drop_table("users")
    # ### end Alembic commands ###
