# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - maketa-frontend

on:
  push:
    branches:
      - try-azure-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'  # npmのキャッシュを有効化
          cache-dependency-path: 'frontend/package-lock.json'  # package-lock.jsonの場所を指定

      - name: Install and Build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: |
          cd frontend
          npm ci  # yarn install --frozen-lockfileの代わり
          npm run build

      - name: Prepare deployment package
        run: |
          cd frontend
          mkdir -p deploy
          cp -r .next/standalone/* deploy/
          cp -r .next deploy/
          mkdir -p deploy/public
          cp -r public/* deploy/public/ || true
          cp package.json deploy/
          cd deploy
          npm ci --omit=dev  # 本番依存関係のみをインストール
          zip -r ../../release.zip . -q -x "**/.git/**" "**/.next/cache/**"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -q

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE42E514FEB34208B102B2640120279F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_63BE05FE5BD944DEA520B31C0089437B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9DC70B829214E2FAF387F622D232F42 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'maketa-frontend'
          slot-name: 'Production'
          package: .
          